"""Add file_hash and timestamp to transactions

Revision ID: 7f8749fa3ef0
Revises: 79ad037c9a70
Create Date: 2025-07-07 01:47:22.474276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8749fa3ef0'
down_revision: Union[str, Sequence[str], None] = '79ad037c9a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
