"""Add transaction_date to transactions

Revision ID: c9dd9e7861e7
Revises: de4ed55c9c57
Create Date: 2025-07-07 02:01:24.783726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dd9e7861e7'
down_revision: Union[str, Sequence[str], None] = 'de4ed55c9c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('file_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
